--///////////////////////////////////////////////////////
--AUTOR:
-- Cristian Gonzalez
--FECHA: 
-- 22/03/2025
--FUNCION:
-- Gestion de Apuestas
--///////////////////////////////////////////////////////
PRINT 'BETS'
GO

IF OBJECT_ID('HEYGIA.BETS') IS NOT NULL
BEGIN
	DROP TABLE HEYGIA.BETS

	IF OBJECT_ID('HEYGIA.BETS') IS NOT NULL
		PRINT '<<< FAILED DROPPING TABLE HEYGIA.BETS >>>'
	ELSE
		PRINT '<<< DROPPED TABLE HEYGIA.BETS >>>'
END
GO
CREATE TABLE HEYGIA.BETS (
    BetId INT IDENTITY(1,1) PRIMARY KEY,
    ClientId INT NOT NULL,
    RouletteId INT NOT NULL,
	BetType VARCHAR(10) NOT NULL, 
    BetValue VARCHAR(10) NOT NULL,
    Amount DECIMAL(10,2) NOT NULL,
	Status VARCHAR(10) NOT NULL DEFAULT 'PENDING', -- 'Pending', 'Won', 'Lost'
    CreatedAt DATETIME NOT NULL DEFAULT GETDATE(),
    FOREIGN KEY (ClientId) REFERENCES HEYGIA.CLIENTS(ClientId)
);

GO

IF OBJECT_ID('HEYGIA.BETS') IS NOT NULL
	PRINT '<<< CREATED TABLE HEYGIA.BETS  >>>'
ELSE
	PRINT '<<< FAILED CREATING TABLE HEYGIA.BETS >>>'
GO

IF @@ERROR != 0
	SELECT '*** ERROR en Script ***'
ELSE
	SELECT 'Finalizo OK ' + RTRIM(CAST(GETDATE() AS NVARCHAR(30)))
GO
